### ISSUE TITLE
Ingen tagg för labb 1

### ISSUE THREAD

**Issue by I-Hansson** [McQueenMG/TDA553-lab1#1]
## CRITICAL ##
Ni behöver tagga den committen som är er inlämning för labb 1. Här finns en guide:
https://docs.github.com/en/desktop/contributing-and-collaborating-using-github-desktop/managing-commits/managing-tags

**Comment by McQueenMG** [comment]
![Skärmavbild 2022-11-27 kl  13 10 31](https://user-images.githubusercontent.com/117281156/204134560-5bbca910-4d00-4683-bd83-1129d3eb7bf6.png)
Hmm, Har gjort det den finns där för mig.

**Comment by I-Hansson** [comment]
Det ser ut som du inte har pushat den commiten. Se till att taggen ligger på master också.

**Comment by McQueenMG** [comment]
Ser det bra ut nu?

**Comment by I-Hansson** [comment]
Perfekt!
